name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - run: npm ci
      - run: npm start
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT
        
      - name: Upload apps.json files
        uses: actions/upload-artifact@v3
        with:
          name: apps-json-${{ steps.date.outputs.date }}
          path: lists/*-apps.json
          retention-days: 3